vertx:
  amqp:
    ssl: true
    jksKeyStore:
      enabled: true
      path: tls/client-keystore.jks
      password: wibble
    jksTrustStore:
      enabled: true
      path: tls/client-truststore.jks
      password: wibble
spring:
  artemis:
    embedded:
      enabled: false # We'll start an embedded broker with an AMQP acceptor ourselves
